name: Release Portfolio

env:
  NODE_VERSION: "14"

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.S3_BUCKET_REGION}}
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Deploy portfolio to S3 bucket
        run: aws s3 sync ./dist/ s3://${{secrets.S3_BUCKET}} --delete
